---
- include: selinux.yml
  tags:
    - selinux
- include: postfix.yml
  tags: 
    - postfix
- include: postfix-tls.yml
  when: postfix_tls_enable
  tags:
    - postfix
- include: mailwatch.yml
  tags:
    - mailwatch
- include: mailscanner.yml
  tags:
    - mailscanner

