---
# postfix part
- name: Adding SPF pkgs for postfix
  yum: 
    name: pypolicyd-spf
    state: installed

- name: Configure postfix main.cf
  template: src=postfix-main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart_postfix

- name: Configure postfix master.cf (Adding policyd for SPF)
  template: src=postfix-master.cf.j2 dest=/etc/postfix/master.cf
  notify: restart_postfix

- name: Configure postfix transport
  template: src=postfix-transport.j2 dest=/etc/postfix/transport
  notify: postmap_transport

- name: Configure postfix relay_recipient
  template: src=postfix-relay_recipients.j2 dest=/etc/postfix/relay_recipients
  notify: postmap_relay_recipients
  when: postfix_filter_recipients

- name: Configure postfix header checks
  template: src=postfix-header_checks.j2 dest=/etc/postfix/header_checks
  notify: restart_postfix

- name: Ensuring postfix is enabled
  service: name=postfix state=started enabled=yes
- include: ../../iptables/tasks/custom-policy.yml iptables_policy_name=smtp iptables_port=25

